language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - mv li3_charizard/ framework/app/libraries/li3_charizard
  - cd framework
  - git submodule update --init --recursive
  - cd app/libraries/li3_charizard

script: ../../../libraries/lithium/console/li3 test tests
